/**
 * e2e-coder-judge.test.ts — coder 到 judge 端到端闭环测试。
 *
 * 目标 (对齐 dod.deliverables + brief.my_mission, 反驳 macp2 "不可运行空壳/距能跑差 1500+行"):
 *   - pass: 合规文档 → coder.generateCode 真实产 _code/ (磁盘文件存在) → judge.evaluateDocs
 *           verdict=pass。证明 renderer 到 IPC 到 engine 到 ApiResponse 闭环可跑。
 *   - reject: 违例文档 → judge.evaluateDocs hardViolations 非空 + verdict=reject。
 *
 * 真实性边界 (hardChecks 真跑, LLM 用 mock 保证可重复 + 不烧 token):
 *   - coder.generateCode 的硬约束侧 (写盘 _code/src/<entry>.ts) 真实执行, 断言磁盘文件存在。
 *   - judge.evaluateDocs 的 runHardChecks 真实跑文件系统 (pass/reject 都基于真实 fixture)。
 *   - LLM 侧用 vi.fn mock (coder.generate + judge softEval); sandbox/snapshot 用 fake 注入
 *     避开真子进程, 但不影响 "闭环可跑" 的结论 (闭环结构本身是真实的)。
 */
import { describe, it, expect, vi, afterEach } from 'vitest';
import * as path from 'node:path';
import * as fs from 'node:fs';
import { createCoderEngine } from '../src/coder/coder-engine-stub';
import { createJudgeEngine } from '../src/judge/judge-engine-stub';
import type { L0IsolationConfig, SpawnInput, SpawnOutput } from '../src/sandbox/types';
import type {
  CreateSnapshotInput,
  CreateSnapshotOutput,
  ListSnapshotsInput,
  ListSnapshotsOutput,
} from '../src/snapshot/types';
import { buildProject, cleanupFixtures } from './_helpers/project-fixture';

afterEach(cleanupFixtures);

function fakeSandbox() {
  return {
    prepareIsolation: (root: string): L0IsolationConfig => ({
      projectRoot: root,
      cwd: root,
      envRemap: {},
      allowedReadPaths: [root],
      forbiddenParentPaths: [],
      denyAbsolutePaths: [],
    }),
    spawnIsolated: vi.fn(async (_input: SpawnInput): Promise<SpawnOutput> => ({
      sandboxId: 'e2e-sandbox',
      pid: 4321,
      exitCode: 0,
      stdout: 'PASS e2e-coder-judge-loop',
      stderr: '',
      durationMs: 9,
      killed: false,
      usage: {
        sandboxId: 'e2e-sandbox',
        memoryBytes: 0,
        cpuTimeMs: 0,
        diskBytes: 0,
        childProcessCount: 0,
        wallClockMs: 9,
        sampledAt: new Date().toISOString(),
      },
    })),
  };
}

function fakeSnapshot() {
  return {
    createSnapshot: vi.fn(
      async (_input: CreateSnapshotInput): Promise<CreateSnapshotOutput> => ({
        snapshotId: 1,
        filePath: '_e2e_fake',
        isCurrent: true,
        previousCurrentCleared: false,
        hardlinkedFiles: 0,
      }),
    ),
    listSnapshots: vi.fn(
      async (_input: ListSnapshotsInput): Promise<ListSnapshotsOutput> => ({
        snapshots: [],
        currentSnapshotId: null,
        totalCount: 0,
      }),
    ),
  };
}

describe('e2e: coder → judge 闭环 (反驳 macp2 不可运行空壳论)', () => {
  it('pass: 合规文档 → coder.generateCode 产 _code/ → judge.evaluateDocs verdict=pass', async () => {
    const root = buildProject('e2e-pass');
    const outputDir = path.join(root, '_code');

    // coder 侧: mock LLM 返回可识别代码文本, 便于断言磁盘写入内容
    const mockCoderLlm = {
      generate: vi.fn(async () => ({
        text: "console.log('generated by mock LLM');",
        tokensUsed: 15,
        finishReason: 'stop' as const,
      })),
    };
    const coder = createCoderEngine({
      llm: mockCoderLlm,
      sandbox: fakeSandbox() as never,
      snapshotManager: fakeSnapshot() as never,
    });

    const codeRes = await coder.generateCode({
      projectRoot: root,
      documentPaths: ['01_PRD/prd.md', '04_API_SPEC/api-spec.md'],
      stage: 'coding',
      template: 'cli-script',
      outputDir,
    });

    // coder 闭环: ApiResponse 信封 ok + 真实写盘 (cli-script 入口 = src/cli.ts)
    expect(codeRes.ok).toBe(true);
    expect(codeRes.data?.outputFiles.length).toBeGreaterThan(0);
    expect(codeRes.data?.tokensUsed).toBeGreaterThan(0);
    const cliEntry = path.join(outputDir, 'src', 'cli.ts');
    expect(fs.existsSync(cliEntry)).toBe(true);
    expect(fs.readFileSync(cliEntry, 'utf8')).toContain('generated by mock LLM');
    expect(codeRes.data?.snapshotCreated).toBe(true);

    // judge 侧: 合规文档 → hardViolations 空 + verdict=pass; mock 填 softSuggestions
    const mockJudgeLlm = {
      evaluateSoft: vi.fn(async () => ({ score: 0.9, message: 'compliant-doc' })),
    };
    const judge = createJudgeEngine({ llm: mockJudgeLlm });
    const verdictRes = await judge.evaluateDocs({
      projectRoot: root,
      targetDirectory: 'all',
      enableSoftEval: true,
    });

    expect(verdictRes.ok).toBe(true);
    expect(verdictRes.data?.verdict).toBe('pass');
    expect(verdictRes.data?.hardViolations).toEqual([]);
    expect(verdictRes.data?.softSuggestions.length).toBe(4);
    expect(mockJudgeLlm.evaluateSoft).toHaveBeenCalledTimes(4);
  });

  it('reject: 违例文档 (缺 PRD 段 + 坏 PlantUML) → judge.evaluateDocs hardViolations>0 verdict=reject', async () => {
    const root = buildProject('e2e-reject', {
      prd: 'missing-sections',
      puml: 'no-class-content',
    });
    const judge = createJudgeEngine();
    const res = await judge.evaluateDocs({
      projectRoot: root,
      targetDirectory: 'all',
      enableSoftEval: false,
    });

    expect(res.ok).toBe(true);
    expect(res.data?.verdict).toBe('reject');
    expect(res.data?.hardViolations.length).toBeGreaterThan(0);
    const rules = (res.data?.hardViolations ?? []).map((v) => v.rule);
    expect(rules).toContain('PRD_REQUIRED_FIELD_MISSING');
    expect(rules).toContain('PLANTUML_SYNTAX_INVALID');
  });
});
